### ISSUE TITLE
Error 6000 (0x1770) Not Approved, on swapOut

### ISSUE THREAD

**Issue by retrofinger** [raydium-io/raydium-sdk-V2-demo#100]
For some reason src/cpmm/swapBaseOut fails on custom CPMM pool (created via createCpmmPool.ts):

**Program log: AnchorError thrown in programs/cp-swap/src/instructions/swap_base_output.rs:20. Error Code: NotApproved. Error Number: 6000. Error Message: Not approved.**

More info:

simulate tx string: [
  'ARd8LARXeWXLbag+77DzFJZNWfFfmoIAd7t5mSzvbIc3ppT3l7ypI/ak6WdjWgJ+QopwKwR7ofFXgVBJrqeUfwmAAQAJEKuWPcwI+3MFVw6V0ygqdznUQOHur7r+kRjCPK9rBPqaUPIhp78OUXwQqUZBtRSlyNRn6HbMznv1dbe9esD7+sS8NAHItHfPgY4zXpz9iheIOQHc13uPGNNhCDdy0Cx4pM5Ck25cr8ssvI/1XJHHfLIYA5Tn8BLeaXa2wdrGUhTNs8lTzkNusbxG8U+D7ZLR5piBiLAy8plzVxDytPlz3C3BMsXwrs/54pqFHOk9rzlEyhCUE6fdiynWOzSWzrt5Da335o2nAiX+/LkOFBdPmzTSQi+IZB+WIzHVxDYv2S1gAwZGb+UhFzL/7K26csOb57yM5bvF9xJrLEObOkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbd9uHXZaGT2cvhRs7reawctIXtX1s3kTqM9YV+/wCpBpuIV/6rgYT7aH9jRhjANdrEOdwa6ztVmKDwAAAAAAEGp9UXGSxcUSGMyUw9SvF/WNruCJuh/UTj29mKAAAAAKkqMRqImIZNIGPI/MtTbh6KME2NU5hMCk6zwUQH1nTnZc2YXwKpPGqdDByCwDe6Yh4wL0pWZvWva+N/UKN8FAaFlP5MTjTO94+/mcHEn7+DS79/yJ02EVwoR2pOg0j68TIIELFlh0GVchT0dlEd6dfpnt24CDRwgDlrEIqjkODX/wEteRaTL+j6jewl5wVPs6RSmqUuc9UOk86mEvzXw6UGBwAJA0BCDwAAAAAABwAFAmDqAAAIAgABfAMAAACrlj3MCPtzBVcOldMoKnc51EDh7q+6/pEYwjyvawT6miAAAAAAAAAAN2hCODJqTlluS3I2V0Zua255c3I5U3hwaDc2dHJQaTKjJ4UAAAAAAKUAAAAAAAAABt324ddloZPZy+FGzut5rBy0he1fWzeROoz1hX7/AKkJBAEKAAsBAQwNAA0OAgEDBAUJCQoPBhg32WJWo0q0rbMJZgAAAAAAAMJYiE0AAAAJAwEAAAEJAA=='
]
//dev/raydium-sdk-V2-demo-master/raydium-sdk-V2-demo/node_modules/@solana/web3.js/src/connection.ts:6043
      throw new SendTransactionError({
            ^
SendTransactionError: Simulation failed. 
Message: Transaction simulation failed: Error processing Instruction 4: custom program error: 0x1770. 
Logs: 
[
  "Program 11111111111111111111111111111111 success",
  "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]",
  "Program log: Instruction: InitializeAccount",
  "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 3443 of 59550 compute units",
  "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success",
  "Program CPMDWBwJDtYax9qW7AyRuVC19Cc4L4Vcy4n2BHAbHkCW invoke [1]",
  "Program log: Instruction: SwapBaseOutput",
  "Program log: AnchorError thrown in programs/cp-swap/src/instructions/swap_base_output.rs:20. Error Code: NotApproved. Error Number: 6000. Error Message: Not approved.",
  "Program CPMDWBwJDtYax9qW7AyRuVC19Cc4L4Vcy4n2BHAbHkCW consumed 18838 of 56107 compute units",
  "Program CPMDWBwJDtYax9qW7AyRuVC19Cc4L4Vcy4n2BHAbHkCW failed: custom program error: 0x1770"
]. 
Catch the `SendTransactionError` and call `getLogs()` on it for full details.
    at Connection.sendEncodedTransaction (//dev/raydium-sdk-V2-demo-master/raydium-sdk-V2-demo/node_modules/@solana/web3.js/src/connection.ts:6043:13)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Connection.sendRawTransaction (//dev/raydium-sdk-V2-demo-master/raydium-sdk-V2-demo/node_modules/@solana/web3.js/src/connection.ts:5999:20)
    at async Connection.sendTransaction (//dev/raydium-sdk-V2-demo-master/raydium-sdk-V2-demo/node_modules/@solana/web3.js/src/connection.ts:5948:14)
    at async execute (//dev/raydium-sdk-V2-demo-master/raydium-sdk-V2-demo/node_modules/@raydium-io/raydium-sdk-v2/src/common/txTool/txTool.ts:472:24) {
  signature: '',
  transactionMessage: 'Transaction simulation failed: Error processing Instruction 4: custom program error: 0x1770',
  transactionLogs: [
    'Program ComputeBudget111111111111111111111111111111 invoke [1]',
    'Program ComputeBudget111111111111111111111111111111 success',
    'Program ComputeBudget111111111111111111111111111111 invoke [1]',
    'Program ComputeBudget111111111111111111111111111111 success',
    'Program 11111111111111111111111111111111 invoke [1]',
    'Program 11111111111111111111111111111111 success',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]',
    'Program log: Instruction: InitializeAccount',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 3443 of 59550 compute units',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
    'Program CPMDWBwJDtYax9qW7AyRuVC19Cc4L4Vcy4n2BHAbHkCW invoke [1]',
    'Program log: Instruction: SwapBaseOutput',
    'Program log: AnchorError thrown in programs/cp-swap/src/instructions/swap_base_output.rs:20. Error Code: NotApproved. Error Number: 6000. Error Message: Not approved.',
    'Program CPMDWBwJDtYax9qW7AyRuVC19Cc4L4Vcy4n2BHAbHkCW consumed 18838 of 56107 compute units',
    'Program CPMDWBwJDtYax9qW7AyRuVC19Cc4L4Vcy4n2BHAbHkCW failed: custom program error: 0x1770'
  ]
}

**Comment by LmingXie** [comment]
Could you tell me what caused this error?

**Comment by chutiange** [comment]
why close?
