### ISSUE TITLE
computeAmountOut not working for amm mintB->mintA

### ISSUE THREAD

**Issue by tushar-sahoo** [raydium-io/raydium-sdk-V2-demo#29]
```
const out = raydium.liquidity.computeAmountOut({
                poolInfo: {
                    ...poolInfo,
                    baseReserve: pool.baseReserve,
                    quoteReserve: pool.quoteReserve,
                },
                amountIn: new BN(amountToSend),
                mintIn: poolInfo.mintB.address, // swap mintB -> mintA, use: poolInfo.mintB.address
                mintOut: poolInfo.mintA.address, // swap mintB -> mintA, use: poolInfo.mintA.address
                slippage: 0.01, // range: 1 ~ 0.0001, means 100% ~ 0.01%
});
```

I get the error below when trying to swap mintB->mintA. mintA->mintB works fine.

```
Error: toke not match
    at Qr.computeAmountOut (/Users/tusharsahoo/Downloads/solana-metaplex/node_modules/@raydium-io/raydium-sdk-v2/lib/index.js:1:251269)
    at main (/Users/tusharsahoo/Downloads/solana-metaplex/rs2.js:99:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    ```

**Comment by cruzshia** [comment]
Looks like you are using old sdk, please update to latest version

**Comment by tushar-sahoo** [comment]
@cruzshia Ya sorry about that. I had one more issue. The slippage value is a little confusing. I want to keep 0.5% slippage so what should I pass here.

**Comment by cruzshia** [comment]
slippage: 0.01, // range: 1 ~ 0.0001, means 100% ~ 0.01%
0.5% => 0.5/100 = 0.005
