### ISSUE TITLE
help, some errors

### ISSUE THREAD

**Issue by xyq-c-cpp** [raydium-io/raydium-sdk-V2-demo#86]
D:\software\nodejs\node.exe -r ts-node/register .\src\api\swap.ts src\config.ts
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
connect to rpc https://go.getblock.io/xxxx in mainnet
D:\code\raydium-sdk-V2-demo\node_modules\@solana\web3.js\src\connection.ts:3383
      throw new SolanaJSONRPCError(
            ^
SolanaJSONRPCError: failed to get token accounts owned by account xxx: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA excluded from account secondary indexes; this RPC method unavailable for key
    at Connection.getTokenAccountsByOwner (D:\code\raydium-sdk-V2-demo\node_modules\@solana\web3.js\src\connection.ts:3383:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async no.fetchWalletTokenAccounts (D:\code\raydium-sdk-V2-demo\node_modules\@raydium-io\raydium-sdk-v2\src\raydium\account\account.ts:95:80) {
  code: -32010,
  data: undefined
}
Process exited with code 1

have somebody meet this questions? tell me if you know why this happened.

**Comment by xyq-c-cpp** [comment]
@cruzshia

**Comment by cruzshia** [comment]
Please check your rpc, it's not coding error
SolanaJSONRPCError
